/interface ethernet
set ether1 mtu=1400

/interface bridge
add name=lo1
add name=lo2

/ip address
add address=192.168.1.3/24 interface=ether1
add address=1.1.1.1/32 interface=lo1
add address=2.2.2.2/32 interface=lo2

/routing rip instance
add disabled=no name=rip redistribute=connected,static update-interval=10

/routing rip interface-template
add disabled=no instance=rip interfaces=all

/system logging add action=memory topics=rip

/log/print follow
/ip/route print