/interface ethernet
set ether1 mtu=1400

/ip address
add address=192.168.1.3/24 interface=ether1 network=192.168.1.0

/interface vxlan
add name=e1 vni=1
add name=e2 vni=2
add name=e3 vni=3
add name=e4 vni=4
add name=e5 vni=5

/interface bridge
add name=switch vlan-filtering=yes

/interface bridge port
add bridge=switch interface=e1
add bridge=switch interface=e2
add bridge=switch interface=e3
add bridge=switch interface=e4
add bridge=switch interface=e5
